(function(){
  "use strict";
  const yearSelect=document.getElementById("qualifyingYear"),leagueSelect=document.getElementById("qualifyingLeague"),searchInput=document.getElementById("qualifyingSearch"),resultsArea=document.getElementById("qualifyingResults"),matchCount=document.getElementById("qualifyingMatchCount"),entryCount=document.getElementById("qualifyingEntryCount");
  let qualifyingRows=[];
  const text=value=>String(value??"").trim();
  const number=value=>Number(text(value).replace(/,/g,""))||0;
  const escapeHtml=value=>text(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  const matchKey=row=>["年度","リーグ","ステージ","試合No","日付","時間","試合"].map(header=>text(row[header])).join("|");
  function displayDate(value){const normalized=text(value).replaceAll("-","/"),match=normalized.match(/^(\d{4})\/(\d{1,2})\/(\d{1,2})$/);return match?`${match[1]}/${match[2].padStart(2,"0")}/${match[3].padStart(2,"0")}`:normalized}
  function populateFilters(){const years=[...new Set(qualifyingRows.map(row=>text(row["年度"])).filter(Boolean))].sort((a,b)=>Number(b)-Number(a)),leagues=[...new Set(qualifyingRows.map(row=>text(row["リーグ"])).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ja"));yearSelect.innerHTML=(years.length?years:["2027"]).map(year=>`<option value="${escapeHtml(year)}">${escapeHtml(year)}</option>`).join("");leagueSelect.innerHTML=`<option value="">すべて</option>${leagues.map(league=>`<option value="${escapeHtml(league)}">${escapeHtml(league)}</option>`).join("")}`}
  function render(){const year=yearSelect.value,league=leagueSelect.value,query=text(searchInput.value).normalize("NFKC").toLowerCase(),filtered=qualifyingRows.filter(row=>{const names=`${text(row["チーム名"])} ${text(row["選手名"])}`.normalize("NFKC").toLowerCase();return(!year||text(row["年度"])===year)&&(!league||text(row["リーグ"])===league)&&(!query||names.includes(query))}),groups=new Map();filtered.forEach(row=>{const key=matchKey(row);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)});const matches=[...groups.values()].sort((a,b)=>`${text(b[0]["日付"])} ${text(b[0]["時間"])} ${text(b[0]["試合No"])}`.localeCompare(`${text(a[0]["日付"])} ${text(a[0]["時間"])} ${text(a[0]["試合No"])}`,"ja",{numeric:true}));matchCount.textContent=String(matches.length);entryCount.textContent=String(filtered.length);if(!matches.length){resultsArea.innerHTML=`<div class="qualifying-empty">${qualifyingRows.length?"条件に一致する予選結果はありません。":"予選結果はまだ登録されていません。"}</div>`;return}resultsArea.innerHTML=matches.map(rows=>{const first=rows[0],sortedRows=[...rows].sort((a,b)=>number(a["着順"])-number(b["着順"]));return`<article class="qualifying-match-card"><header class="qualifying-match-head"><strong>${escapeHtml(displayDate(first["日付"]))}　${escapeHtml(first["リーグ"]||"予選")}</strong><small>${escapeHtml(first["試合"]||`試合No ${first["試合No"]||"-"}`)}${first["時間"]?`｜${escapeHtml(first["時間"])}`:""}</small></header><table class="qualifying-match-table"><thead><tr><th>着順</th><th>チーム</th><th>選手</th><th>スコア</th><th>得点</th></tr></thead><tbody>${sortedRows.map(row=>{const score=number(row["スコア"]),scoreClass=score<0?"qualifying-score-negative":"qualifying-score-positive";return`<tr><td class="qualifying-rank">${escapeHtml(row["着順"]||"-")}</td><td>${escapeHtml(row["チーム名"])}</td><td>${escapeHtml(row["選手名"])}</td><td class="${scoreClass}">${score>0?"+":""}${score.toFixed(1)}</td><td>${number(row["得点"]).toLocaleString("ja-JP")}</td></tr>`}).join("")}</tbody></table></article>`}).join("")}
  async function init(){try{qualifyingRows=await HLDB.loadData("qualifyingMatches",true);populateFilters();render()}catch(error){console.error("予選結果CSVの読み込みに失敗しました",error);yearSelect.innerHTML='<option value="2027">2027</option>';resultsArea.innerHTML='<div class="qualifying-error">予選結果を読み込めませんでした。時間をおいて再読み込みしてください。</div>'}if(window.lucide)window.lucide.createIcons()}
  yearSelect.addEventListener("change",render);leagueSelect.addEventListener("change",render);searchInput.addEventListener("input",render);init();
})();
