(function(){
  "use strict";
  const matches=["第一試合","第二試合","第三試合","第四試合","第五試合","第六試合"];
  const teams={
    "Aリーグ":["武装","MJ東京","ZOO","SILVER WOLVES","最強位ズ","電光石火"],
    "Bリーグ":["さわやかMJ野郎の会","Team MJ lovers","教室生☆KSC","チートイズ","おたまーず","Brave Revengers"]
  };
  const players={"武装":["ツナマヨ","年賀状","乙子","しんじゃうツモ"],"MJ東京":["Blue-K18","aimoni","選手A","選手B"],"ZOO":["かじ","選手C","選手D"],"SILVER WOLVES":["田口淳之介","店長倍損の上司","選手E"]};
  const views=["inputView","confirmView","listView","urlView"];
  const $=id=>document.getElementById(id);
  let pending=null,currentLeague="Aリーグ",selectedKey="";
  const today=()=>new Date().toLocaleDateString("sv-SE");
  const store=()=>JSON.parse(localStorage.getItem("hldbScoreEntryDemo")||"{}");
  const save=data=>localStorage.setItem("hldbScoreEntryDemo",JSON.stringify(data));
  function show(id){views.forEach(v=>$(v).hidden=v!==id);$("navInput").classList.toggle("active",id==="inputView");$("navList").classList.toggle("active",id==="listView"||id==="urlView");scrollTo(0,0)}
  function normalizeScore(value){return String(value).trim().replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-65248)).replace(/[＋]/g,"+").replace(/[－−―ー]/g,"-").replace(/[，,．]/g,".").replace(/\s/g,"")}
  function teamOptions(league,selected){return teams[league].map(t=>`<option${t===selected?" selected":""}>${t}</option>`).join("")}
  function playerOptions(team,selected){const list=players[team]||["選手を選択","選手A","選手B","選手C"];return list.map(p=>`<option${p===selected?" selected":""}>${p}</option>`).join("")}
  function buildPlayers(){const host=$("playerInputs");host.innerHTML="";for(let i=0;i<4;i++){const team=teams[$("leagueInput").value][i]||teams[$("leagueInput").value][0];const card=document.createElement("section");card.className="panel player-card";card.innerHTML=`<h2>入力${i+1}</h2><label>チーム<select class="team-select">${teamOptions($("leagueInput").value,team)}</select></label><label>選手<select class="player-select">${playerOptions(team,"")}</select></label><label>スコア<input class="score-input" inputmode="decimal" placeholder="例：+52.8"></label>`;host.appendChild(card);const ts=card.querySelector(".team-select"),ps=card.querySelector(".player-select");ts.addEventListener("change",()=>ps.innerHTML=playerOptions(ts.value,""));}}
  function getInput(){const rows=[...document.querySelectorAll(".player-card")].map(card=>{const raw=normalizeScore(card.querySelector(".score-input").value);return{team:card.querySelector(".team-select").value,player:card.querySelector(".player-select").value,raw,score:Number(raw)}});return{date:today(),league:$("leagueInput").value,match:$("matchInput").value,rows}}
  function validate(data){if(data.rows.some(r=>r.raw===""||!Number.isFinite(r.score)))return"4人全員のスコアを数字で入力してください。";if(new Set(data.rows.map(r=>r.player)).size!==4)return"同じ選手が重複しています。";const total=data.rows.reduce((n,r)=>n+r.score,0);if(Math.abs(total)>.051)return`スコア合計が ${total>0?"+":""}${total.toFixed(1)} pt です。入力内容を確認してください。`;return""}
  function renderConfirm(data){data.rows.sort((a,b)=>b.score-a.score);$("confirmMatch").innerHTML=`<div><strong>リーグ</strong>${data.league}</div><div><strong>試合</strong>${data.match}</div>`;$("confirmPlayers").innerHTML=data.rows.map((r,i)=>`<div class="confirm-row"><span class="confirm-rank">${i+1}位</span><span>${r.team}</span><span>${r.player}</span><span class="${r.score<0?"score-negative":"score-positive"}">${r.score>0?"+":""}${r.score.toFixed(1)}</span></div>`).join("");const total=data.rows.reduce((n,r)=>n+r.score,0);$("totalPanel").className="panel total-panel total-valid";$("totalPanel").innerHTML=`<span>合計</span><strong>${total.toFixed(1)} pt</strong>`}
  function seedFor(date,league){const data=store(),base=`${date}|${league}|`;matches.forEach((m,i)=>{const key=base+m;if(!data[key])data[key]={date,league,match:m,time:`${18-Math.floor(i/2)}:${String(42-i*7).padStart(2,"0")}`,url:i===2||i===4?"":`https://example.com/match-${i+1}`,rows:[]}});save(data)}
  function renderList(){const date=$("listDate").value||today();seedFor(date,currentLeague);const data=store(),items=matches.map(m=>data[`${date}|${currentLeague}|${m}`]).filter(Boolean),done=items.filter(x=>x.url).length;$("listSummary").innerHTML=`<div>入力済み<span class="summary-number">${items.length}</span></div><div class="summary-missing">未入力<span class="summary-number">${items.length-done}</span>試合</div><div class="summary-done">URL入力済み<span class="summary-number">${done}</span>試合</div>`;$("matchList").innerHTML=items.map(item=>{const key=`${item.date}|${item.league}|${item.match}`,missing=!item.url;return`<article class="match-card ${missing?"needs-url":""}"><div><div class="match-name">${item.match}</div><div class="match-time">送信 ${item.time}</div></div><div><span class="status score-ok">● スコア確認済み</span><span class="status ${missing?"url-missing":"url-done"}">${missing?"⚠ URL未入力<br><small>入力が必要です</small>":"✓ URL入力済み"}</span></div><button class="match-action" data-key="${key}">${missing?"URLを入力する":"URLを確認・変更"} ›</button></article>`}).join("");document.querySelectorAll(".match-action").forEach(b=>b.addEventListener("click",()=>openUrl(b.dataset.key)))}
  function openUrl(key){selectedKey=key;const item=store()[key];$("urlTitle").textContent=item.match;$("urlMatchInfo").innerHTML=`<div class="match-summary"><span><strong>${item.league}</strong></span><span>送信 ${item.time}</span><span class="status ${item.url?"url-done":"url-missing"}">${item.url?"✓ URL入力済み":"⚠ URL未入力"}</span></div>`;$("matchUrl").value=item.url||"";$("urlMessage").hidden=true;show("urlView")}
  $("leagueInput").addEventListener("change",buildPlayers);buildPlayers();$("listDate").value=today();
  $("scoreForm").addEventListener("submit",e=>{e.preventDefault();const data=getInput(),error=validate(data);$("formMessage").hidden=!error;$("formMessage").textContent=error;if(error)return;pending=data;renderConfirm(data);show("confirmView")});
  $("backToInput").onclick=()=>show("inputView");$("submitScores").onclick=()=>{const data=store(),key=`${pending.date}|${pending.league}|${pending.match}`;data[key]={...pending,time:new Date().toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"}),url:data[key]?.url||""};save(data);$("successModal").hidden=false};$("closeSuccess").onclick=()=>{$("successModal").hidden=true;$("listDate").value=pending.date;currentLeague=pending.league;document.querySelectorAll(".league-tab").forEach(t=>t.classList.toggle("active",t.dataset.league===currentLeague));renderList();show("listView")};
  $("navInput").onclick=()=>show("inputView");$("navList").onclick=()=>{renderList();show("listView")};document.querySelectorAll(".league-tab").forEach(t=>t.onclick=()=>{currentLeague=t.dataset.league;document.querySelectorAll(".league-tab").forEach(x=>x.classList.toggle("active",x===t));renderList()});$("listDate").onchange=renderList;function moveDate(days){const d=new Date($("listDate").value+"T12:00:00");d.setDate(d.getDate()+days);$("listDate").value=d.toLocaleDateString("sv-SE");renderList()}$("previousDate").onclick=()=>moveDate(-1);$("nextDate").onclick=()=>moveDate(1);$("todayButton").onclick=()=>{$("listDate").value=today();renderList()};
  $("saveUrl").onclick=()=>{const value=$("matchUrl").value.trim();if(value&&!/^https?:\/\//i.test(value)){$("urlMessage").textContent="http:// または https:// から始まるURLを入力してください。";$("urlMessage").hidden=false;return}const data=store();data[selectedKey].url=value;save(data);$("urlMessage").hidden=true;renderList();show("listView")};$("backToListTop").onclick=$("backToListBottom").onclick=()=>{renderList();show("listView")};
})();
